/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.view;

/**
 *
 * @author aris-
 */
public class SimulationView extends javax.swing.JFrame {

    /**
     * Creates new form SimulationView
     */
    public SimulationView() {
        initComponents();

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reloj = new javax.swing.JLabel();
        walkIn_PatientsImg = new javax.swing.JLabel();
        patientsByAppointmentImg = new javax.swing.JLabel();
        dia = new javax.swing.JLabel();
        walkIn_Patients = new javax.swing.JLabel();
        patientsByAppointment = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        WaitingImg = new javax.swing.JLabel();
        AttendingImg = new javax.swing.JLabel();
        punto = new javax.swing.JRadioButton();
        punto1 = new javax.swing.JRadioButton();
        punto2 = new javax.swing.JRadioButton();
        punto3 = new javax.swing.JRadioButton();
        punto4 = new javax.swing.JRadioButton();
        punto5 = new javax.swing.JRadioButton();
        punto6 = new javax.swing.JRadioButton();
        punto7 = new javax.swing.JRadioButton();
        finishedImg = new javax.swing.JLabel();
        waiting = new javax.swing.JLabel();
        attending = new javax.swing.JLabel();
        finished = new javax.swing.JLabel();
        velocidadBt = new javax.swing.JButton();
        velocidadInt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIMULATION");

        reloj.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        reloj.setForeground(new java.awt.Color(51, 0, 255));
        reloj.setText("00:00:00");
        reloj.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Hour", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Lucida Sans Typewriter", 3, 18), new java.awt.Color(204, 0, 204))); // NOI18N

        walkIn_PatientsImg.setIcon(new javax.swing.ImageIcon("C:\\Users\\aris-\\OneDrive\\Documentos\\NetBeansProjects\\simulacion\\src\\main\\java\\com\\mycompany\\Img\\paciente.png")); // NOI18N

        patientsByAppointmentImg.setIcon(new javax.swing.ImageIcon("C:\\Users\\aris-\\OneDrive\\Documentos\\NetBeansProjects\\simulacion\\src\\main\\java\\com\\mycompany\\Img\\paciente.png")); // NOI18N

        dia.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        dia.setForeground(new java.awt.Color(51, 0, 255));
        dia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dia.setText("0");
        dia.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Day", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Lucida Sans Typewriter", 3, 18), new java.awt.Color(204, 0, 204))); // NOI18N

        walkIn_Patients.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        walkIn_Patients.setForeground(new java.awt.Color(51, 0, 255));
        walkIn_Patients.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        walkIn_Patients.setText("0");
        walkIn_Patients.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Walk-in patients", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Lucida Sans Typewriter", 3, 18), new java.awt.Color(204, 0, 204))); // NOI18N

        patientsByAppointment.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        patientsByAppointment.setForeground(new java.awt.Color(51, 0, 255));
        patientsByAppointment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        patientsByAppointment.setText("0");
        patientsByAppointment.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Patients by appointment", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Lucida Sans Typewriter", 3, 18), new java.awt.Color(204, 0, 204))); // NOI18N

        WaitingImg.setIcon(new javax.swing.ImageIcon("C:\\Users\\aris-\\OneDrive\\Documentos\\NetBeansProjects\\simulacion\\src\\main\\java\\com\\mycompany\\Img\\pacientes en espera.png")); // NOI18N

        AttendingImg.setIcon(new javax.swing.ImageIcon("C:\\Users\\aris-\\OneDrive\\Documentos\\NetBeansProjects\\simulacion\\src\\main\\java\\com\\mycompany\\Img\\atencion.png")); // NOI18N

        punto.setSelected(true);
        punto.setEnabled(false);
        punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntoActionPerformed(evt);
            }
        });

        punto1.setSelected(true);
        punto1.setEnabled(false);
        punto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                punto1ActionPerformed(evt);
            }
        });

        punto2.setSelected(true);
        punto2.setEnabled(false);
        punto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                punto2ActionPerformed(evt);
            }
        });

        punto3.setSelected(true);
        punto3.setEnabled(false);
        punto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                punto3ActionPerformed(evt);
            }
        });

        punto4.setSelected(true);
        punto4.setEnabled(false);
        punto4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                punto4ActionPerformed(evt);
            }
        });

        punto5.setSelected(true);
        punto5.setEnabled(false);
        punto5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                punto5ActionPerformed(evt);
            }
        });

        punto6.setSelected(true);
        punto6.setEnabled(false);
        punto6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                punto6ActionPerformed(evt);
            }
        });

        punto7.setSelected(true);
        punto7.setEnabled(false);
        punto7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                punto7ActionPerformed(evt);
            }
        });

        finishedImg.setIcon(new javax.swing.ImageIcon("C:\\Users\\aris-\\OneDrive\\Documentos\\NetBeansProjects\\simulacion\\src\\main\\java\\com\\mycompany\\Img\\atendido.jpg")); // NOI18N

        waiting.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        waiting.setForeground(new java.awt.Color(51, 0, 255));
        waiting.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        waiting.setText("0                 0                 0");
        waiting.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "PBA       Waiting       WIP", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Lucida Sans Typewriter", 3, 18), new java.awt.Color(204, 0, 204))); // NOI18N

        attending.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        attending.setForeground(new java.awt.Color(51, 0, 255));
        attending.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        attending.setText("0");
        attending.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Attending", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Lucida Sans Typewriter", 3, 18), new java.awt.Color(204, 0, 204))); // NOI18N

        finished.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        finished.setForeground(new java.awt.Color(51, 0, 255));
        finished.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        finished.setText("0");
        finished.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Finished", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Lucida Sans Typewriter", 3, 18), new java.awt.Color(204, 0, 204))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(WaitingImg)
                        .addGap(46, 46, 46)
                        .addComponent(punto)
                        .addGap(41, 41, 41)
                        .addComponent(punto1)
                        .addGap(40, 40, 40)
                        .addComponent(punto2)
                        .addGap(49, 49, 49))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(waiting, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(punto3)
                        .addGap(55, 55, 55)
                        .addComponent(AttendingImg)
                        .addGap(40, 40, 40)
                        .addComponent(punto4))
                    .addComponent(attending, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(punto5)
                        .addGap(40, 40, 40)
                        .addComponent(punto6)
                        .addGap(49, 49, 49)
                        .addComponent(punto7)
                        .addGap(18, 18, 18)
                        .addComponent(finishedImg)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(finished, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(waiting)
                    .addComponent(attending)
                    .addComponent(finished))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(punto5)
                                    .addComponent(punto4)
                                    .addComponent(punto6)
                                    .addComponent(punto7))
                                .addGap(132, 132, 132))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(finishedImg)
                                .addGap(69, 69, 69))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AttendingImg)
                        .addGap(69, 69, 69))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(punto1)
                                    .addComponent(punto)
                                    .addComponent(punto2)
                                    .addComponent(punto3)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(WaitingImg)))
                        .addContainerGap())))
        );

        velocidadBt.setFont(new java.awt.Font("SansSerif", 3, 24)); // NOI18N
        velocidadBt.setText("SPEED");
        velocidadBt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        velocidadInt.setFont(new java.awt.Font("Gill Sans MT", 3, 18)); // NOI18N
        velocidadInt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        velocidadInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velocidadIntActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel2.setText("MILLISECONDS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(patientsByAppointmentImg))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(patientsByAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 288, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(walkIn_Patients, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(walkIn_PatientsImg)
                        .addGap(50, 50, 50)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reloj)
                        .addGap(38, 38, 38))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(velocidadBt)
                .addGap(18, 18, 18)
                .addComponent(velocidadInt, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(378, 378, 378))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(walkIn_Patients)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(walkIn_PatientsImg))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(patientsByAppointment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(patientsByAppointmentImg))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(dia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(reloj)))
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(velocidadBt)
                    .addComponent(velocidadInt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puntoActionPerformed

    private void punto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_punto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_punto1ActionPerformed

    private void punto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_punto2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_punto2ActionPerformed

    private void punto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_punto3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_punto3ActionPerformed

    private void punto4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_punto4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_punto4ActionPerformed

    private void punto5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_punto5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_punto5ActionPerformed

    private void punto6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_punto6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_punto6ActionPerformed

    private void punto7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_punto7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_punto7ActionPerformed

    private void velocidadIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velocidadIntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velocidadIntActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimulationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimulationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimulationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimulationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimulationView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AttendingImg;
    private javax.swing.JLabel WaitingImg;
    public javax.swing.JLabel attending;
    public javax.swing.JLabel dia;
    public javax.swing.JLabel finished;
    public javax.swing.JLabel finishedImg;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel patientsByAppointment;
    public javax.swing.JLabel patientsByAppointmentImg;
    public javax.swing.JRadioButton punto;
    public javax.swing.JRadioButton punto1;
    public javax.swing.JRadioButton punto2;
    public javax.swing.JRadioButton punto3;
    public javax.swing.JRadioButton punto4;
    public javax.swing.JRadioButton punto5;
    public javax.swing.JRadioButton punto6;
    public javax.swing.JRadioButton punto7;
    public javax.swing.JLabel reloj;
    public javax.swing.JButton velocidadBt;
    public javax.swing.JTextField velocidadInt;
    public javax.swing.JLabel waiting;
    public javax.swing.JLabel walkIn_Patients;
    public javax.swing.JLabel walkIn_PatientsImg;
    // End of variables declaration//GEN-END:variables
}
